version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(cargo)"
    open-pull-requests-limit: 50

  # Keep GitHub Actions up to date.
  # <https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot>
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
