# GitHub Actions workflow to build
# Node.js bindings documentation
# and upload it to the web server.
# Built documentation is available at <https://js.delta.chat/>

name: Generate & upload node.js documentation

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: npm install and generate documentation
        working-directory: node
        run: |
          npm i --ignore-scripts
          npx typedoc
          mv docs js

      - name: Upload
        uses: horochx/deploy-via-scp@1.1.0
        with:
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          host: "delta.chat"
          port: 22
          local: "node/js"
          remote: "/var/www/html/"
